name: DMT-Lootdrops
version: '${project.version}'
main: be.nateoncaprisun.dmtlootdrops.LootdropPlugin
authors: [ NateOnCaprisun, EddieFreddie, Jazzkuh]
description: DailyMT Lootdrops
commands:
  lootdrop: